# Generated by Django 3.2.4 on 2021-08-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdapp', '0004_rename_mobile_contactinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.IntegerField(max_length=13),
        ),
    ]
