# Generated by Django 3.2.4 on 2021-08-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wdapp', '0005_alter_contactinfo_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='sno',
            new_name='eno',
        ),
    ]
