# Generated by Django 3.2.4 on 2021-08-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdapp', '0006_rename_sno_contactinfo_eno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
